#!/usr/bin/env php
<?php
$cmds[] ='iptables -N lefilter';                                   //this will add new chain with name lerules and below are the rules 
$cmds[] ='iptables -A lefilter -m state --state NEW -j ACCEPT';
$cmds[] ='iptables -A lefilter -m string --string "GET /.well-known/acme-challenge/" --algo kmp --from 52 --to 53 -j ACCEPT';
$cmds[] ='iptables -A lefilter -m string --string "GET /.freepbx-known" --algo kmp --from 52 --to 53 -j ACCEPT';
$cmds[] ='iptables -A lefilter -j RETURN';
$cmds[] ='iptables -D fpbxfirewall -p tcp -m state --state ESTABLISHED,RELATED -j ACCEPT';
$cmds[] ='iptables -I fpbxfirewall -p tcp ! --dport 80 -m state --state ESTABLISHED,RELATED -j ACCEPT';
$cmds[] ='iptables -I INPUT -p tcp --dport 80 -j lefilter';
$cmds[] ='iptables-save';

foreach($cmds as $cmd) {
	exec($cmd . "&>> /var/log/asterisk/cermanlerules.log");
}
