#!/usr/bin/env php
<?php
if(file_exists("/var/spool/asterisk/certman.iptablesLEenable_running")) {
	$cmds[] ='/usr/sbin/iptables -w -S fpbxfirewall | grep "tcp\s.*RELATED,ESTABLISHED" | cut -d" " -f 2- | xargs -rL1 iptables -w -D';
	$cmds[] ='/usr/sbin/iptables -w -I fpbxfirewall -p tcp -m state --state ESTABLISHED,RELATED -j ACCEPT';
	$cmds[] ='/usr/sbin/iptables -w -S INPUT | grep lefilter | cut -d " " -f 2- | xargs -rL1 iptables -w -D';
	$cmds[] ='/usr/sbin/iptables -w -F lefilter';
	$cmds[] ='/usr/sbin/iptables -w -X lefilter';
	$cmds[] ='/usr/sbin/iptables-save';
	foreach($cmds as $cmd) {
		exec($cmd . "&>> /var/log/asterisk/cermanlerules.log");
	}
	exec('rm /var/spool/asterisk/certman.iptablesLEenable_running');
}
